fix(FEC-10811): floating show two bottom bar for second
kaltura/playkit-js-ui pull request #599
Opened 2021-05-09 14:38 UTC by Yuvalke

### Description of the Changes

Issue: the first event of resize/scroll doesn't take into account.
Solution: trigger the function on the leading edge instead of the trail.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-05-09 17:36 UTC, RoyBregman approved these changes

2021-05-09 17:54 UTC, OrenMe requested changes

2021-05-09 17:54 UTC, OrenMe commented on src/utils/debounce.js
> +    if (immediate && !timeout) origFunc.apply(context, args);
Do not use inline ifs without curly brackets.
@yairans letw make sure we have lint rule to make sure this is not possible

2021-05-09 17:56 UTC, OrenMe commented
@Yuvalke sid you mean to write "isn't taken into account"?

2021-05-10 11:14 UTC, yairans approved these changes

2021-05-12 13:12 UTC, merged