FEC-10666
kaltura/playkit-js-ui pull request #628
Opened 2021-07-25 15:49 UTC by JonathanTGold

### Description of the Changes

We wish to add a simple indication that would allow millennials to know the quality they are watching.

Requirements
For resolutions, where height is between 720 (included) and 2160 (excluded) add an HD indication.
For resolutions, where height is between 2160 (included) and 4320 (excluded) add a 4K indication.
For resolutions, where height is above 4320 (included) add a 8K indication.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-07-27 11:41 UTC, RoyBregman commented on src/components/dropdown/dropdown.js
> +  getActiveOptionLabel(): Object {
rename

2021-08-04 14:58 UTC, yairans requested changes

2021-08-08 14:14 UTC, yairans commented on src/components/smart-container/_smart-container.scss
> -          overflow: hidden;
need to support long label (FEC-7236)

2021-08-08 14:24 UTC, yairans commented on src/styles/_dropdown.scss
> +    .label-badge {
```suggestion
    .label-badge.badge-icon {
```

2021-08-08 14:26 UTC, yairans commented on src/styles/_dropdown.scss
> +      &[class*='badge-icon'] {
same

2021-08-09 11:19 UTC, yairans approved these changes

2021-08-09 15:29 UTC, yairans approved these changes

2021-08-10 09:04 UTC, yairans approved these changes

2021-08-10 09:07 UTC, merged