feat(FEC-12113): Add Side Panels Management to player UI
kaltura/playkit-js-ui pull request #674
Opened 2022-05-02 14:17 UTC by JonathanTGold

### Description of the Changes

Expose public enums needed across plugins

solves: FEC-12113

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2022-05-04 14:24 UTC, yairans requested changes

2022-05-04 14:24 UTC, yairans commented on src/reducers/shell.js
> +  Playback: 'Playback',
There are more

2022-05-09 09:13 UTC, JonathanTGold commented on src/reducers/shell.js
> +  Before: 'Before',
removed

2022-05-11 12:09 UTC, yairans requested changes

2022-05-12 08:08 UTC, yairans commented on src/reducers/shell.js
> +  Playback: 'Playback',
what about them?

2022-05-12 08:55 UTC, JonathanTGold commented on src/reducers/shell.js
> +  Playback: 'Playback',
fixed

2022-05-12 09:26 UTC, yairans approved these changes

2022-05-16 16:42 UTC, merged