fix(FEC-12911): keyboard Navigation - Advanced Captions modal
kaltura/playkit-js-ui pull request #724
Opened 2023-02-06 14:44 UTC by lianbenjamin

### Description of the Changes

**the issue:**
current issue is that when navigating to cvaa overlay, the focus should be on the active Sample button, but the focus is actually on a language button element (the globe).

**root cause:**
this happens because the a11yKeyboard wrapper is triggering unmount for the language smart container, after a11yKeyboard didMount for the cvaa overlay.

**solution:**
add useEffect to the sample button component to focus to the active element, once mounted.
In addition, did some minor changes to make sampleCaptions component cleaner.

Solves FEC-12911

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-02-06 15:00 UTC, SivanA-Kaltura requested changes

2023-02-06 15:00 UTC, SivanA-Kaltura commented on src/components/cvaa-overlay/main-captions_window.js
> +            isActive={props.player.textStyle.isEqual(this.captionsStyleYellow)}>
can textStyle be undefined ?

2023-02-06 15:32 UTC, lianbenjamin commented on src/components/cvaa-overlay/main-captions_window.js
> +            isActive={props.player.textStyle.isEqual(this.captionsStyleYellow)}>
no, we set it in setup-helpers

2023-02-08 14:44 UTC, semarche-kaltura approved these changes

2023-02-09 13:32 UTC, SivanA-Kaltura approved these changes

2023-02-09 14:52 UTC, merged