fix(FEC-12519): Side panels should be overlaid the entire player when player size is "SMALL" (smaller then 480px)
kaltura/playkit-js-ui pull request #738
Opened 2023-03-12 17:36 UTC by JonathanTGold

### Description of the Changes

solves FEC-12519

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-03-13 10:24 UTC, SivanA-Kaltura requested changes

2023-03-13 10:24 UTC, SivanA-Kaltura commented on src/components/player-area/player-areas-utils.js
> +  if (playerWidth < PLAYER_BREAK_POINTS.SMALL) {
why are you making the calculation again if you can get PLAYER_SIZE from state.shell ?

2023-03-13 15:43 UTC, semarche-kaltura approved these changes

2023-03-16 14:26 UTC, SivanA-Kaltura approved these changes

2023-03-16 15:01 UTC, merged