docs(FEC-13049): Update docs
kaltura/playkit-js-ui pull request #743
Opened 2023-03-21 10:00 UTC by JonathanTGold

### Description of the Changes

solvs FEC-13049

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-03-21 10:04 UTC, semarche-kaltura commented on docs/ui-components.md
> +        get: remove
it should be string?

2023-03-21 10:05 UTC, giladna approved these changes

2023-04-19 10:33 UTC, giladna requested changes

2023-04-19 10:33 UTC, giladna commented on docs/ui-components.md
> +        get: remove
```suggestion
        get: 'remove'
```

2023-04-24 07:01 UTC, merged