fix(FEC-13377): Player v7| audio player entry info| Entry info does not change when changing audio entries
kaltura/playkit-js-ui pull request #800
Opened 2023-10-01 15:22 UTC by SivanA-Kaltura

### Description of the Changes

Audio player details component does not re-render on entry change, probably due to its location in the component hierarchy. 
To force the component to re-render - added a listener to source change events.

Resolves FEC-13377

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-10-01 17:59 UTC, JonathanTGold requested changes
you just need to add shouldUpdate={true} prop to PlayerArea component in playback.js and the problem should be solved 

your listener and refactor is redundant

2023-10-02 09:42 UTC, JonathanTGold approved these changes

2023-10-02 09:44 UTC, SivanA-Kaltura commented
@JonathanTGold As we've spoken earlier, it looks like player state changes too quickly and does not trigger the re-render of the component, so using an event listener is an ugly but working solution

2023-10-02 09:52 UTC, semarche-kaltura approved these changes

2023-10-02 09:53 UTC, merged