fix(FEC-13535): add classnames to expandable text
kaltura/playkit-js-ui pull request #828
Opened 2023-12-26 08:36 UTC by semarche-kaltura

### Description of the Changes

resolves: https://kaltura.atlassian.net/browse/FEC-13535

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2024-01-08 09:05 UTC, lianbenjamin requested changes

2024-01-08 09:05 UTC, lianbenjamin commented on src/components/expandable-text/expandable-text.js
> +    <div className={['expandable-text-container', isTextExpanded ? 'text-expanded' : ''].join(' ')}>
hey @semarche-kaltura , is it possible to write the class names from styles like we usually do, instead of hard-coding them? or export them to const?

2024-01-08 11:06 UTC, SivanA-Kaltura requested changes

2024-01-08 11:06 UTC, SivanA-Kaltura commented on src/components/expandable-text/expandable-text.js
>    return (
why is this needed ?

2024-01-08 11:07 UTC, SivanA-Kaltura requested changes

2024-01-08 11:07 UTC, SivanA-Kaltura commented on src/components/expandable-text/expandable-text.js
> +    <div className={['expandable-text-container', isTextExpanded ? 'text-expanded' : ''].join(' ')}>
why is this needed ? this would create a coupling with these texts to somewhere else, and it could break if it's changed in one of the repos

2024-02-08 15:05 UTC, SivanA-Kaltura approved these changes

2024-02-12 20:15 UTC, merged