fix(ADA-190): Focus back on the player from other elements
kaltura/playkit-js-ui pull request #848
Opened 2024-01-25 15:58 UTC by Tzipi-kaltura

### Description of the Changes

**Issue:**
There is no option to focus on the player via keyboard when the control bar is hidden

**Fix:**
Listen to tab press on the page, display the control bar and move the focus to the playerContainer or to the last element on the player (according to the user press: tab or shift tab)

#### Resolves [ADA-190](https://kaltura.atlassian.net/browse/ADA-190)

2024-01-25 16:48 UTC, JonathanTGold requested changes

2024-01-25 16:48 UTC, JonathanTGold commented on src/components/shell/shell.tsx
> +      playerContainer.setAttribute('tabindex', '0');
You should not manipulate the dom directly but set conditional attribute in jsx

2024-01-25 16:59 UTC, JonathanTGold requested changes
Is not it the same issue ?
https://github.com/kaltura/playkit-js-ui/pull/775

2024-01-29 08:35 UTC, JonathanTGold requested changes
https://github.com/kaltura/playkit-js-ui/pull/775

See this PR

2024-01-30 07:40 UTC, Tzipi-kaltura commented
> #775
> 
> See this PR

it's a different issue. here we need to focus on the player after control bar is hidden. in your pr it's moving to focus after click play.

2024-02-04 10:42 UTC, JonathanTGold requested changes
after through investigation with Tzippi , the flow should be as following:

the root of the issue is that the player doesn’t contain any **tabblable** elements (since bottom bar is removed from the DOM completely on hover state = false)

1. fix difference bottom bar behaviour between mouse click and tab movements (the bottom bar should disappear in tab movement as well)
2. bottom bar should show up (as it does on hover) when focued with tab movements

2024-03-06 09:50 UTC, SivanA-Kaltura commented
@Tzipi-kaltura Closing this PR as this issue will be solved by a separate PR

2024-03-06 09:50 UTC, closed without merging