feat(FEC-13912): Captions product analytics
kaltura/playkit-js-ui pull request #890
Opened 2024-06-10 23:39 UTC by semarche-kaltura

### Description of the Changes

Captions product analytics

Resolves: https://kaltura.atlassian.net/browse/FEC-13912

**Issue:**

**Fix:**

2024-06-13 08:20 UTC, SivanA-Kaltura requested changes

2024-06-17 09:29 UTC, semarche-kaltura commented on src/components/event-dispatcher/event-dispatcher-provider.tsx
> +  if (currentStyles?.textAlign !== newStyles?.textAlign) {
textAlign is string, condition works good

2024-06-17 09:47 UTC, semarche-kaltura commented on src/components/event-dispatcher/event-dispatcher-provider.tsx
> +  // @ts-ignore
missed type in Playkit-js

2024-06-19 10:11 UTC, SivanA-Kaltura approved these changes

2024-06-19 10:54 UTC, merged